name: customer_connect
description: A new Flutter application.
publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_easyloading: ^3.0.5
  provider: ^6.0.3
  shared_preferences: ^2.1.2
  http: ^1.2.2
  image_picker: ^1.0.0
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.0.5
  geolocator: ^13.0.2
  syncfusion_flutter_pdfviewer: ^28.1.36
  shape_of_view_null_safe: ^3.0.0
  kenburns_nullsafety: ^1.0.1
  connectivity_plus: ^6.1.1
  dotted_border: ^2.0.0+3
  fluttertoast: ^8.2.2
  geocoding: ^3.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  webview_flutter: ^4.7.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.9
  file_picker: ^8.0.3
  dropdown_search: ^6.0.1
  flutter_image_compress: ^2.3.0
  flutter_otp_text_field: ^1.4.0+2
  package_info_plus: ^8.1.2
  html: ^0.15.4
  open_file: ^3.5.10
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/pbgpl_logo.png"
  min_sdk_android: 21

